In [2]:
import argparse
import sys
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow.contrib.rnn as rnn
import tensorflow.contrib.layers as layers
# from text_loader import TextLoader

from tensorflow.contrib.layers import batch_norm

from sklearn import metrics
print(tf.__version__)

1.9.0


In [3]:
data=pd.read_csv('celeba-dataset/newdataset.csv')

In [4]:
data

image_id  has bags under eyes  is bald  has bangs  has black hair  \
0       000001.jpg                    0        0          0               0   
1       000002.jpg                    1        0          0               0   
2       000003.jpg                    0        0          0               0   
3       000004.jpg                    0        0          0               0   
4       000005.jpg                    0        0          0               0   
5       000006.jpg                    0        0          0               0   
6       000007.jpg                    1        0          0               1   
7       000008.jpg                    1        0          0               1   
8       000009.jpg                    0        0          1               0   
9       000010.jpg                    0        0          0               0   
10      000011.jpg                    0        0          0               0   
11      000012.jpg                    0        0          0               1   
12      000013.jpg                    0        0          0               0   
13      000014.jpg                    0        0          0               0   
14      000015.jpg                    1        0          0               0   
15      000016.jpg                    1        0          0               0   
16      000017.jpg                    0        0          0               0   
17      000018.jpg                    0        0          0               0   
18      000019.jpg                    0        0          0               0   
19      000020.jpg                    0        0          0               0   
20      000021.jpg                    0        0          0               0   
21      000022.jpg                    0        0          0               0   
22      000023.jpg                    0        0          0               0   
23      000024.jpg                    0        0          0               0   
24      000025.jpg                    0        0          0               0   
25      000026.jpg                    0        0          0               0   
26      000027.jpg                    0        0          0               1   
27      000028.jpg                    0        0          0               0   
28      000029.jpg                    0        0          0               0   
29      000030.jpg                    1        0          0               0   
...            ...                  ...      ...        ...             ...   
202569  202570.jpg                    0        0          0               1   
202570  202571.jpg                    0        0          0               0   
202571  202572.jpg                    0        0          0               0   
202572  202573.jpg                    0        0          0               0   
202573  202574.jpg                    0        0          0               0   
202574  202575.jpg                    0        0          0               0   
202575  202576.jpg                    0        0          0               0   
202576  202577.jpg                    0        0          0               0   
202577  202578.jpg                    0        0          0               0   
202578  202579.jpg                    1        0          0               0   
202579  202580.jpg                    0        0          1               0   
202580  202581.jpg                    0        0          0               0   
202581  202582.jpg                    1        0          0               0   
202582  202583.jpg                    0        0          0               0   
202583  202584.jpg                    0        0          0               0   
202584  202585.jpg                    0        0          0               0   
202585  202586.jpg                    1        0          0               0   
202586  202587.jpg                    0        0          0               0   
202587  202588.jpg                    0        0          0 

In [5]:
x=data['sentence']
y=np.array(data.iloc[:,1:26]).tolist()
# y=list(data.iloc[0:,1:2])
# y = [1 if x == '1' else 0 for x in data['is chubby'] ]
y

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
 [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,

In [6]:
FLAGS = None
MAX_DOCUMENT_LENGTH = 30

EMBEDDING_SIZE = 20
n_words = 0
MAX_LABEL = 25
WORDS_FEATURE = 'words'
learning_rate = 0.01

sess = tf.Session()


In [7]:

def estimator_spec_for_softmax_classification (logits, labels, mode):

    """Returns EstimatorSpec instance for softmax classification."""

#     predicted_classes = tf.argmax(logits, 1)
    predicted_classes = tf.sigmoid(logits)
    
    print("666")
    print(predicted_classes)
#     print(type(tf.Session().run(predicted_classes)))

    # case 1) inference mode
    
    # ModeKey가 PREDICT이면 inference mode이다. inference는 학습시킨 모델을 새로운 데이터에 적용시키는 것을 말한다.
    if mode == tf.estimator.ModeKeys.PREDICT: 
        
        print("ppp")
        return tf.estimator.EstimatorSpec(mode=mode, predictions={'class': predicted_classes, 'prob': tf.nn.softmax(logits), 'logits': logits})

    
    # case 2) training mode
    
#     onehot_labels = tf.one_hot(labels, MAX_LABEL, 1, 0)
    onehot_labels = labels

    print("777")
    print(onehot_labels)
    print(type(logits))
    
    loss = tf.losses.softmax_cross_entropy(onehot_labels=onehot_labels, logits=logits)    
    
    if mode == tf.estimator.ModeKeys.TRAIN:

        print("ttt")
        optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)

        train_op = optimizer.minimize(loss, global_step=tf.train.get_global_step())

        return tf.estimator.EstimatorSpec(mode, loss=loss, train_op=train_op, predictions=logits)

    # case 3) evaluation mode
    
    print("eee!")
    print(labels)
    print(predicted_classes)
    eval_metric_ops = {'accuracy': tf.metrics.accuracy(labels=labels, predictions=predicted_classes)}
    print("eee?")
    return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)

In [8]:
def rnn_model(features, labels, mode):
    print(features, labels, mode)
#     anotherlabels = tf.identity(labels, "hihi")
    tf.shape(labels, 'hihi')

    """RNN model to predict from sequence of words to a class."""
    
    # 단어들의 index를 embeddings로 바꾼다. 
    # [n_words(단어 개수), EMBEDDING_SIZE]의 크기를 가지는 matrix를 만들고 순서를 나타내는 단어들의 index를 
    # [batch_size, sequence_length, EMBEDDING_SIZE]에 mapping 한다.
    
    # word_vectors와 word_list를 만든다.
    word_vectors = tf.contrib.layers.embed_sequence(features[WORDS_FEATURE], vocab_size=n_words, embed_dim=EMBEDDING_SIZE)
    word_list = tf.unstack(word_vectors, axis=1)

    
    # embedding size와 같은 hidden size를 가지는 GUR cell을 만든다.
    cell = tf.contrib.rnn.GRUCell(EMBEDDING_SIZE)

    
    # MAX_DOCUMENT_LENGTH의 길이를 가지는 RNN을 만든다. 그리고 각 유닛에 input으로 word_list를 준다.
    # (output, state)쌍이 return된다.
    _, encoding = tf.contrib.rnn.static_rnn(cell, word_list, dtype=tf.float32)

    ##########중요 여기바꿔야
    # 마지막 유닛의 state 값을 softmax classification의 feature로 넘겨준다.
    logits = tf.layers.dense(encoding, MAX_LABEL, activation=None)
#     print(features[WORDS_FEATURE].eval())
    print("111")
    print(encoding)
    
#     if mode == tf.estimator.ModeKeys.TRAIN:
#         logits = tf.contrib.layers.batch_norm(logits,center=True, scale=True,is_training=True)
#     else:
#         logits = tf.contrib.layers.batch_norm(logits,center=True, scale=True,is_training=False)
    
#     logits=tf.nn.relu(logits, 'relu')
    
    return estimator_spec_for_softmax_classification(logits=logits, labels=labels, mode=mode)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
y

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
 [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,

In [11]:
128

128

In [12]:
# train data set, test data set을 나눠준다.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 4)
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = np.array(y_test) # tensorflow input으로 사용될 수 있는 자료형으로 변환시켜줘야 한다.
print(x_train)
print(y_train)
print(x_test)
print(y_test)
# 단어들을 우리가 원하는 sequence length로 맞추어 준다.(embedding 해주기 전 단계) 위의 사진 참고
vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(MAX_DOCUMENT_LENGTH)

x_transform_train = vocab_processor.fit_transform(x_train) # 둘의 차이는?
x_transform_test = vocab_processor.transform(x_test)
x_train = np.array(list(x_transform_train))
x_test = np.array(list(x_transform_test))


n_words = len(vocab_processor.vocabulary_)
print (vocab_processor.vocabulary_)
print('Total words : %d', n_words)

# 모델을 만들어준다.(여기서는 위에서 정의한 rnn_model을 사용한다.)
model_fn = rnn_model
classifier = tf.estimator.Estimator(model_fn=model_fn)


print("111")
# Train
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x = {WORDS_FEATURE : x_train},
    y = y_train,
    batch_size = 128,
    num_epochs = 1,
    shuffle = True) # shuffle = True : 


# Set up logging for predictions
tensors_to_log = {"hihi": "hihi"}
logging_hook = tf.train.LoggingTensorHook(
    tensors=tensors_to_log, every_n_iter=50)


['A smiling woman with black hair has no beard and oval face'
 'A opening her mouth slightly woman has no beard'
 'A smiling and young woman has high cheekbones' ...
 'A woman with bangs has a pointy nose'
 'A young man with oval face has sideburns and black hair'
 'A man has no beard']
[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 1]
 ...
 [0 0 1 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
['A man with gray hair and no beard is smiling'
 'A opening hmouth slightly man with black hair has no beard and high cheekbones'
 'A woman has brown hair' ...
 'A wearing eyeglasses woman with high cheekbones and black hair is smiling'
 'A woman has blond hair' 'A woman is young']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 1]]
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflo

In [13]:
classifier.train(input_fn = train_input_fn, steps = 100, hooks=[logging_hook])


INFO:tensorflow:Calling model_fn.
{'words': <tf.Tensor 'random_shuffle_queue_DequeueUpTo:1' shape=(?, 30) dtype=int64>} Tensor("random_shuffle_queue_DequeueUpTo:2", shape=(?, 25), dtype=int64, device=/device:CPU:0) train
111
Tensor("rnn/gru_cell/add_29:0", shape=(?, 20), dtype=float32)
666
Tensor("Sigmoid:0", shape=(?, 25), dtype=float32)
777
Tensor("random_shuffle_queue_DequeueUpTo:2", shape=(?, 25), dtype=int64, device=/device:CPU:0)
<class 'tensorflow.python.framework.ops.Tensor'>
ttt
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmp16lg3fbs/model.ckpt.


InternalError: Blas GEMM launch failed : a.shape=(128, 40), b.shape=(40, 40), m=128, n=40, k=40
	 [[Node: rnn/gru_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rnn/gru_cell/concat, rnn/gru_cell/gates/kernel/read)]]
	 [[Node: softmax_cross_entropy_loss/value/_157 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1367_softmax_cross_entropy_loss/value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'rnn/gru_cell/MatMul', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2909, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-4a8ac0780143>", line 1, in <module>
    classifier.train(input_fn = train_input_fn, steps = 100, hooks=[logging_hook])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 366, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1119, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1132, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "<ipython-input-8-b5c4d939a0f3>", line 23, in rnn_model
    _, encoding = tf.contrib.rnn.static_rnn(cell, word_list, dtype=tf.float32)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn.py", line 1315, in static_rnn
    (output, state) = call_cell()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn.py", line 1302, in <lambda>
    call_cell = lambda: cell(input_, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 339, in __call__
    *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 329, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 703, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 488, in call
    array_ops.concat([inputs, state], 1), self._gate_kernel)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 2014, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4279, in mat_mul
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(128, 40), b.shape=(40, 40), m=128, n=40, k=40
	 [[Node: rnn/gru_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rnn/gru_cell/concat, rnn/gru_cell/gates/kernel/read)]]
	 [[Node: softmax_cross_entropy_loss/value/_157 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1367_softmax_cross_entropy_loss/value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [132]:
# train data set, test data set을 나눠준다.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 4)
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = np.array(y_test) # tensorflow input으로 사용될 수 있는 자료형으로 변환시켜줘야 한다.
print(x_train)
print(y_train)
print(x_test)
print(y_test)
# 단어들을 우리가 원하는 sequence length로 맞추어 준다.(embedding 해주기 전 단계) 위의 사진 참고
vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(MAX_DOCUMENT_LENGTH)

x_transform_train = vocab_processor.fit_transform(x_train) # 둘의 차이는?
x_transform_test = vocab_processor.transform(x_test)
x_train = np.array(list(x_transform_train))
x_test = np.array(list(x_transform_test))


n_words = len(vocab_processor.vocabulary_)
print (vocab_processor.vocabulary_)
print('Total words : %d', n_words)

# 모델을 만들어준다.(여기서는 위에서 정의한 rnn_model을 사용한다.)
model_fn = rnn_model
classifier = tf.estimator.Estimator(model_fn=model_fn)


print("111")
# Train
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x = {WORDS_FEATURE : x_train},
    y = y_train,
    batch_size = 128,
    num_epochs = 1,
    shuffle = True) # shuffle = True : 


# Set up logging for predictions
tensors_to_log = {"hihi": "hihi"}
logging_hook = tf.train.LoggingTensorHook(
    tensors=tensors_to_log, every_n_iter=50)



classifier.train(input_fn = train_input_fn, steps = 100, hooks=[logging_hook])

# Predict
test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x = {WORDS_FEATURE : x_test},
    y = y_test,
    num_epochs = 1,
    shuffle = False)
predictions = classifier.predict(input_fn = test_input_fn)
y_predicted = np.array(list(p for p in predictions))
print(y_predicted)
# Score using tensorflow
score = classifier.evaluate(input_fn = test_input_fn)
print('Accuracy (tensorflow): {0:f}'.format(score['accuracy']))


In [12]:
def main(unused_argv):
    global n_words
    global vocab_processor
    global classifier

    
    # train data set, test data set을 나눠준다.
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 4)
    x_train = np.array(x_train)
    x_test = np.array(x_test)
    y_train = np.array(y_train)
    y_test = np.array(y_test) # tensorflow input으로 사용될 수 있는 자료형으로 변환시켜줘야 한다.
    print(x_train)
    print(y_train)
    print(x_test)
    print(y_test)
    # 단어들을 우리가 원하는 sequence length로 맞추어 준다.(embedding 해주기 전 단계) 위의 사진 참고
    vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(MAX_DOCUMENT_LENGTH)
    
    x_transform_train = vocab_processor.fit_transform(x_train) # 둘의 차이는?
    x_transform_test = vocab_processor.transform(x_test)
    x_train = np.array(list(x_transform_train))
    x_test = np.array(list(x_transform_test))
    
    
    n_words = len(vocab_processor.vocabulary_)
    print (vocab_processor.vocabulary_)
    print('Total words : %d', n_words)
    
    # 모델을 만들어준다.(여기서는 위에서 정의한 rnn_model을 사용한다.)
    model_fn = rnn_model
    classifier = tf.estimator.Estimator(model_fn=model_fn)
    
    
    print("111")
    # Train
    train_input_fn = tf.estimator.inputs.numpy_input_fn(
        x = {WORDS_FEATURE : x_train},
        y = y_train,
        batch_size = len(x_train),
        num_epochs = None,
        shuffle = True) # shuffle = True : 
    classifier.train(input_fn = train_input_fn, steps = 100)
    
    # Predict
    test_input_fn = tf.estimator.inputs.numpy_input_fn(
        x = {WORDS_FEATURE : x_test},
        y = y_test,
        num_epochs = 1,
        shuffle = False)
    predictions = classifier.predict(input_fn = test_input_fn)
    y_predicted = np.array(list(p['class'] for p in predictions))
    
    # Score using tensorflow
    score = classifier.evaluate(input_fn = test_input_fn)
    print('Accuracy (tensorflow): {0:f}'.format(score['accuracy']))
    print()

In [13]:
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--test_with_fake_data',
        default = False,
        help = 'Test the example code with fake data',
        action = 'store_true')
    parser.add_argument(
        '--bow model',
        default = False,
        help = 'Run with BOW model instead of RNN',
        action = 'store_true')
    FLAGS, unparsed = parser.parse_known_args()
    tf.app.run(main=main, argv = [sys.argv[0]] + unparsed)

['A smiling woman with black hair has no beard and oval face'
 'A opening her mouth slightly woman has no beard'
 'A smiling and young woman has high cheekbones' ...
 'A woman with bangs has a pointy nose'
 'A young man with oval face has sideburns and black hair'
 'A man has no beard']
[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 1]
 ...
 [0 0 1 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
['A man with gray hair and no beard is smiling'
 'A opening hmouth slightly man with black hair has no beard and high cheekbones'
 'A woman has brown hair' ...
 'A wearing eyeglasses woman with high cheekbones and black hair is smiling'
 'A woman has blond hair' 'A woman is young']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 1]]
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflo

ResourceExhaustedError: OOM when allocating tensor with shape[162079,30,20] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: EmbedSequence/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@Adam/Assign"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](EmbedSequence/embeddings/read, random_shuffle_queue_DequeueMany/_147, EmbedSequence/embedding_lookup/axis)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: softmax_cross_entropy_loss/value/_155 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_919_softmax_cross_entropy_loss/value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'EmbedSequence/embedding_lookup', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-dca3f0899829>", line 14, in <module>
    tf.app.run(main=main, argv = [sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "<ipython-input-12-163b4cfe8081>", line 43, in main
    classifier.train(input_fn = train_input_fn, steps = 100)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 366, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1119, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1132, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "<ipython-input-8-b5c4d939a0f3>", line 13, in rnn_model
    word_vectors = tf.contrib.layers.embed_sequence(features[WORDS_FEATURE], vocab_size=n_words, embed_dim=EMBEDDING_SIZE)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/encoders.py", line 142, in embed_sequence
    return embedding_ops.embedding_lookup(embeddings, ids)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/embedding_ops.py", line 308, in embedding_lookup
    transform_fn=None)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/embedding_ops.py", line 131, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 2666, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3141, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[162079,30,20] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: EmbedSequence/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@Adam/Assign"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](EmbedSequence/embeddings/read, random_shuffle_queue_DequeueMany/_147, EmbedSequence/embedding_lookup/axis)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: softmax_cross_entropy_loss/value/_155 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_919_softmax_cross_entropy_loss/value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.



In [ ]:
vocab_processor.vocabulary_.reverse(47)

In [ ]:
classifier.predict()

In [ ]:

# train data set, test data set을 나눠준다.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 4)
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = np.array(y_test) # tensorflow input으로 사용될 수 있는 자료형으로 변환시켜줘야 한다.
print(x_train)
print(y_train)
print(x_test)
print(y_test)
# 단어들을 우리가 원하는 sequence length로 맞추어 준다.(embedding 해주기 전 단계) 위의 사진 참고
vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(MAX_DOCUMENT_LENGTH)

x_transform_train = vocab_processor.fit_transform(x_train) # 둘의 차이는?
x_transform_test = vocab_processor.transform(x_test)
x_train = np.array(list(x_transform_train))
x_test = np.array(list(x_transform_test))


In [ ]:
test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x = {WORDS_FEATURE : x_test},
    y = y_test,
    num_epochs = 1,
    shuffle = False)

# Score using tensorflow
score = classifier.evaluate(input_fn = test_input_fn)
print('Accuracy (tensorflow): {0:f}'.format(score['accuracy']))
print(score)

In [ ]:
for p in predictions:
    print(p)